### ISSUE TITLE
kubebox crashes on pending containers

### ISSUE THREAD

**Issue by galan** [astefanutti/kubebox#12]
Pressing enter on a pending pod will exit kubebox with the following stacktrace:
```
TypeError: Cannot read property 'slice' of undefined
    at updateStatsFromCAdvisor (/kubebox/client.js:3679:151)
    at ListTable.Dashboard.pods_table.on (/kubebox/client.js:3617:21)
    at ListTable.EventEmitter._emit (/kubebox/client.js:6029:20)
    at ListTable.EventEmitter.emit (/kubebox/client.js:6052:12)
    at ListTable.List.enterSelected (/kubebox/client.js:19641:8)
    at ListTable.<anonymous> (/kubebox/client.js:19174:14)
    at ListTable.EventEmitter._emit (/kubebox/client.js:6029:20)
    at ListTable.EventEmitter.emit (/kubebox/client.js:6052:12)
    at Program.<anonymous> (/kubebox/client.js:22728:15)
    at Program.emit (events.js:160:13)
pod default/kubebox terminated (Error)

```

**Comment by astefanutti** [comment]
Ah that's a bug that I want to fix for a long time! Kubebox tries to fetch resources usage stats.

Thanks for the report. Will fix it ASAP.
