### ISSUE TITLE
kubebox version 0.5.0 windows amd64 binary

### ISSUE THREAD

**Issue by vlinx** [astefanutti/kubebox#48]
It fails to run, see error output below:

```
λ kubebox-windows-v0.5.0.exe
C:\Apps\Bin\bundle.js:22988
  if (!this.program.isAlt) return;
                    ^

TypeError: Cannot read property 'isAlt' of undefined
    at Screen.leave (C:\Apps\Bin\bundle.js:22988:21)
    at Screen.destroy (C:\Apps\Bin\bundle.js:23090:8)
    at C:\Apps\Bin\bundle.js:22895:14
    at Array.forEach (<anonymous>)
    at process.on.Screen._exceptionHandler (C:\Apps\Bin\bundle.js:22894:30)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)

λ systeminfo
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17763 N/A Build 17763
System Type:               x64-based PC
```

**Comment by astefanutti** [comment]
I've just re-uploaded the windows binary for v0.5.0, that should contain the fix. Could you please give it a try? Thanks!

**Comment by vlinx** [comment]
The newer version has been tested. It is now working as expected. Thanks.
