### ISSUE TITLE
kubebox for windows not running

### ISSUE THREAD

**Issue by FrankAnk** [astefanutti/kubebox#72]
kubebox for Windows doesn't work, i'm getting the following stacktrace:

```
c:\Tools>kubebox
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'c:\Tools\__nexe_stdin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at Object.<anonymous> (c:\Tools\kubebox.exe:352:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at _third_party_main.js:38:36
    at NativeModule.compile (internal/bootstrap/loaders.js:364:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:176:18)
    at process.nextTick (internal/bootstrap/node.js:249:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 ```

**Comment by astefanutti** [comment]
Thanks for the report. Could you try with version 0.6.1 to confirm it's a regression from previous versions?

**Comment by FrankAnk** [comment]
I have the same problem with version 0.6.1

**Comment by astefanutti** [comment]
Could you please try with the latest 0.9.0 release?

**Comment by astefanutti** [comment]
Let me close this. Feel free to re-open if that's still an issue.

**Comment by endlesstravel** [comment]
same issue :
![image](https://user-images.githubusercontent.com/10757838/126150862-e75e486b-be27-45dd-a706-6794a41d5e44.png)
